version: '3'
services:
  dashboard:
    image: jerben/dashboard
    container_name: dashboard
    environment:
      - DATABASE_URL=http://db:5984
      - DATABASE_USER=couchdb
      - DATABASE_PASSWORD=couchdb
    ports:
      - 80:3000
    depends_on:
      - db
  db:
    image: couchdb
    container_name: couchdb
    ports:
      - 5984:5984
  db_ui:
    image: sosedoff/pgweb
    container_name: postgres-ui
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    ports:
      - 8081:8081
    depends_on:
      - db
    restart: unless-stopped
