version: '3'
services:
  dashboard:
    image: jerben/dashboard
    ports:
      - 80:3000
  db:
    image: postgres:10
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
  db_ui:
    image: sosedoff/pgweb
    container_name: postgres-ui
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    ports:
      - 8081:8081
    depends_on:
      - db
    restart: unless-stopped
