version: '3'
services:
  dashboard:
    build:
      context: ./board
    environment:
      - DATABASE_URL=http://docstore:5984/db
      - DATABASE_USER=couchdb
      - DATABASE_PASSWORD=couchdb
      - HTTP_PORT=3000
    ports:
      - 3000:3000
    depends_on:
      - docstore
    command: ["./wait-for-it.sh", "docstore:5984", "--", "java", "-jar", "dashboard-standalone.jar"]
  docstore:
    image: couchdb
    ports:
      - 5984:5984
  db:
    image: postgres:10
    restart: always
  web:
    build:
      context: ./web
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - ./web:/myap
    ports:
      - 3001:3001
    depends_on:
      - db
  router:
    build:
      context: ./router
    ports:
      - 8080:8080
    depends_on:
      - dashboard
      - web
  pgweb:
    restart: always
    image: sosedoff/pgweb
    ports:
        - 8081:8081
    environment:
        - DATABASE_URL=postgres://postgres:@db:5432/myapp_development?sslmode=disable
    depends_on:
        - db
