# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#

clj_app: &clj_app
  docker:
    - image: circleci/clojure:lein-2.7.1
  environment:
    LEIN_ROOT: "true"
    JVM_OPTS: -Xmx3200m
  steps:
    - checkout
    - run:
        command: |
          cd $CIRCLE_JOB
          lein test
          lein eastwood

rails_app: &rails_app
  docker:
    - image: circleci/ruby:2.4-node
      environment:
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        BUNDLE_PATH: vendor/bundle
        PGHOST: 127.0.0.1
        PGUSER: circleci-demo-ruby
        RAILS_ENV: test
    - image: circleci/postgres:9.5-alpine
      environment:
        POSTGRES_USER: circleci-demo-ruby
        POSTGRES_DB: rails_blog
        POSTGRES_PASSWORD: ""
  steps:
    - checkout
    - run:
        command: |
          cd $CIRCLE_JOB
          bundle install
          dockerize -wait tcp://localhost:5432 -timeout 1m
          bin/rails db:schema:load --trace
          rails test

version: 2
jobs:
  board:
    <<: *clj_app
  web:
    <<: *rails_app
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - board
      - web
