# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 10e12253d3b465d8ad61cb21956e379239f36e14928142495aceb5c1b130d5eb2a03776064bacbf6b1a5ef318cb7674809882643da75bce18d1d77564a86c64f

test:
  secret_key_base: 380d485f80a1067a61ad367a762673b8a9178e609d59df69871cdb95b5a501d8ea1d81a227767f5a4c265ba5d7bd173d40099dd4f697e047225986cdb86b4365

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
